/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // getstartedSidebar: [{type: 'autogenerated', dirName: '.'}],

  getstartedSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "概述",
    },
    {
      type: "category",
      label: "快速开始",
      collapsed: false,
      collapsible: true,
      items: [
        {
          type: "doc",
          id: "deploy-hyperlane",
          label: "部署到新链",
        },
        {
          type: "doc",
          id: "guides/deploy-warp-route",
          label: "桥接代币",
        },
        {
          type: "doc",
          id: "deploy-hyperlane-troubleshooting",
          label: "故障排除",
        },
      ],
    },
    {
      type: "category",
      label: "Warp 路由",
      link: {
        type: "doc",
        id: "protocol/warp-routes/warp-routes-overview",
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "reference/applications/warp-routes",
          label: "Warp 路由接口",
        },
        {
          type: "doc",
          id: "protocol/warp-routes/warp-routes-types",
          label: "Warp 路由类型",
        },
        {
          type: "doc",
          id: "protocol/warp-routes/warp-routes-example-usage",
          label: "Warp 路由使用示例",
        },
      ],
    },
    {
      type: "doc",
      id: "reference/applications/interchain-account",
      label: "跨链账户",
    },
    {
      type: "category",
      label: "指南",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "guides/deploy-warp-route-UI",
          label: "部署桥接UI",
        },
        {
          type: "doc",
          id: "guides/local-testnet-setup",
          label: "本地设置：在Anvil节点间发送消息",
        },
        {
          type: "category",
          label: "Warp 路由",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "protocol/warp-routes/warp-routes-yield-routes",
              label: "部署收益路由",
            },
            {
              type: "doc",
              id: "protocol/warp-routes/warp-routes-custom-gas-fast-native",
              label: "通过自定义Gas代币快速原生转账",
            },
            {
              type: "doc",
              id: "guides/extending-warp-route",
              label: "扩展Warp路由",
            },
            {
              type: "doc",
              id: "guides/xerc20-warp-route-guide",
              label: "部署xERC20 Warp路由",
            },
            {
              type: "doc",
              id: "guides/deploy-svm-warp-route",
              label: "部署SVM Warp路由",
            },
            {
              type: "doc",
              id: "guides/deploy-evm-svm-warp-route",
              label: "部署EVM <> SVM Warp路由",
            },
            {
              type: "doc",
              id: "guides/manage-warp-route-limits",
              label: "管理Warp路由限制",
            },
          ],
        },
        {
          type: "category",
          label: "投入生产",
          link: {
            type: "doc",
            id: "production",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "category",
              label: "核心部署",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "doc",
                  id: "guides/update-mailbox-default-ism",
                  label: "更新邮箱默认ISM",
                },
                {
                  type: "doc",
                  id: "guides/transfer-mailbox-ownership",
                  label: "转移邮箱所有权",
                },
              ],
            },
            {
              type: "category",
              label: "Warp路由部署",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "doc",
                  id: "guides/remove-trusted-relayer",
                  label: "移除受信任中继器",
                },
                {
                  type: "doc",
                  id: "guides/transfer-warp-route-ownership",
                  label: "转移所有权",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Hyperlane浏览器",
          link: {
            type: "doc",
            id: "guides/explorer/explorer",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "guides/explorer/configuring-pi-chains",
              label: "在Hyperlane浏览器中配置新链",
            },
            {
              type: "doc",
              id: "guides/explorer/graphql-api",
              label: "GraphQL API",
            },
          ],
        },
        {
          type: "doc",
          id: "guides/create-custom-hook-and-ism",
          label: "创建Hook/ISM",
        },
        {
          type: "doc",
          id: "guides/deploy-hyperlane-local-agents",
          label: "使用本地代理部署Hyperlane",
        },
      ],
    },
  ],
  protocolSidebar: [
    {
      type: "doc",
      id: "protocol/protocol-overview",
      label: "概述",
    },
    {
      type: "category",
      label: "协议",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "category",
          label: "邮箱",
          link: {
            type: "doc",
            id: "protocol/mailbox",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "category",
              label: "通用消息传递",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "doc",
                  id: "reference/messaging/send",
                  label: "发送消息",
                },
                {
                  type: "doc",
                  id: "reference/messaging/receive",
                  label: "接收消息",
                },
              ],
            },
            {
              type: "doc",
              id: "protocol/interchain-gas-payment",
              label: "跨链 Gas 支付",
            },
            {
              type: "category",
              label: "Post-Dispatch Hooks",
              link: {
                type: "doc",
                id: "reference/hooks/overview",
              },
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "doc",
                  id: "reference/hooks/interchain-gas",
                  label: "跨链 Gas",
                },
                {
                  type: "doc",
                  id: "reference/hooks/op-stack",
                  label: "OP Stack",
                },
                {
                  type: "doc",
                  id: "reference/hooks/arbitrum-L2-to-L1",
                  label: "Arbitrum L2 到 L1",
                },
                {
                  type: "doc",
                  id: "reference/hooks/polygon-pos",
                  label: "Polygon PoS",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "跨链安全模块",
          link: {
            type: "doc",
            id: "protocol/ISM/modular-security",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "protocol/ISM/sequence-diagram",
              label: "时序图",
            },
            {
              type: "doc",
              id: "protocol/ISM/custom-ISM",
              label: "覆盖默认ISM",
            },
            {
              type: "category",
              label: "标准ISM",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "category",
                  label: "多重签名ISM",
                  link: {
                    type: "doc",
                    id: "protocol/ISM/multisig-ISM",
                  },
                  items: [
                    {
                      type: "doc",
                      id: "reference/latencies",
                      label: "延迟",
                    },
                  ],
                },
                {
                  type: "doc",
                  id: "protocol/ISM/routing-ISM",
                  label: "路由 ISM",
                },
                {
                  type: "doc",
                  id: "protocol/ISM/aggregation-ISM",
                  label: "聚合 ISM",
                },
                {
                  type: "doc",
                  id: "protocol/ISM/ccip-read-ISM",
                  label: "CCIP-Read ISM",
                },
              ],
            },
            {
              type: "category",
              label: "社区 ISM",
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: "doc",
                  id: "protocol/ISM/third-party-ISMs/wormhole-ISM",
                  label: "Wormhole ISM",
                },
                {
                  type: "doc",
                  id: "protocol/ISM/third-party-ISMs/optimistic-ISM",
                  label: "Optimistic ISM",
                },
                {
                  type: "doc",
                  id: "protocol/ISM/third-party-ISMs/OPStack-ISM",
                  label: "OP Stack ISM",
                },
                {
                  type: "doc",
                  id: "protocol/ISM/third-party-ISMs/polygon-POS-ISM",
                  label: "Polygon PoS ISM",
                },
                {
                  type: "doc",
                  id: "protocol/ISM/third-party-ISMs/arbitrum-L2-to-L1-ISM",
                  label: "Arbitrum L2 到 L1 ISM",
                },
              ],
            },
            {
              type: "category",
              label: "经济安全",
              link: {
                type: "doc",
                id: "protocol/economic-security/economic-security",
              },
              items: [
                {
                  type: "doc",
                  id: "protocol/economic-security/hyperlane-avs",
                  label: "Hyperlane AVS",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "代理",
          link: {
            type: "doc",
            id: "protocol/agents",
          },
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "protocol/agents/relayer",
              label: "中继器",
            },
            {
              type: "doc",
              id: "protocol/agents/validators",
              label: "验证器",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "开发者工具",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "reference/cli",
          label: "命令行工具",
        },
        {
          type: "doc",
          id: "reference/cosmos-sdk",
          label: "Cosmos SDK",
        },
        {
          type: "category",
          label: "库",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "reference/libraries/mailboxclient",
              label: "邮箱客户端",
            },
            {
              type: "doc",
              id: "reference/libraries/router",
              label: "路由器",
            },
            {
              type: "doc",
              id: "reference/libraries/typecasts",
              label: "类型转换",
            },
            {
              type: "doc",
              id: "reference/libraries/message",
              label: "消息",
            },
            {
              type: "doc",
              id: "reference/libraries/hookmetadata",
              label: "标准 Hook 元数据",
            },
          ],
        },
        {
          type: "category",
          label: "开发者提示",
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "guides/developer-tips/unit-testing",
              label: "单元测试",
            },
            {
              type: "doc",
              id: "guides/token-faucets",
              label: "代币水龙头",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Alt-VM 实现与指南",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "protocol/non-evm-implementations",
          label: "Alt-VM 实现",
        },
        {
          type: "doc",
          id: "guides/implementation-guide",
          label: "实现指南",
        },
      ],
    },
    {
      type: "category",
      label: "部署",
      items: [
        {
          type: "category",
          label: "合约地址",
          items: [
            {
              type: "doc",
              id: "reference/addresses/mailbox-addresses",
              label: "邮箱",
            },
            {
              type: "doc",
              id: "reference/addresses/interchain-gas-paymaster",
              label: "跨链 gas 支付主管（Hook）",
            },
            {
              type: "doc",
              id: "reference/addresses/storage-gas-oracle",
              label: "存储 Gas 预言机",
            },
            {
              type: "doc",
              id: "reference/addresses/merkle-tree",
              label: "默克尔树（Hook）",
            },
            {
              type: "doc",
              id: "reference/addresses/validator-announce",
              label: "验证器公告",
            },
            {
              type: "doc",
              id: "reference/addresses/proxy-admin",
              label: "代理管理员",
            },
            {
              type: "doc",
              id: "reference/addresses/test-recipient",
              label: "测试接收者",
            },
            {
              type: "doc",
              id: "reference/addresses/interchain-account-router",
              label: "跨链账户路由器",
            },
          ],
        },
        {
          type: "doc",
          id: "reference/default-ism-validators",
          label: "默认 ISM 验证器",
        },
        {
          type: "doc",
          id: "reference/domains",
          label: "域",
        },
        {
          type: "doc",
          id: "reference/registries",
          label: "注册表",
        },
      ],
    },
    {
      type: "category",
      label: "资源",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "guides/message-debugging",
          label: "消息传递调试",
        },
        {
          type: "doc",
          id: "reference/glossary",
          label: "术语表",
        },
        {
          type: "doc",
          id: "faq",
          label: "常见问题",
        },
        {
          type: "doc",
          id: "reference/audits",
          label: "审计",
        },
      ],
    },
  ],
  /*
  guidesSidebar: [
    {
      type: "doc",
      id: "guides/deploy-hyperlane-local-agents",
      label: "使用本地代理部署 Hyperlane",
    },
    {
      type: "doc",
      id: "guides/implementation-guide",
      label: "实现指南",
    },
  ],*/

  operateSidebar: [
    {
      type: "doc",
      id: "operate/overview-agents",
      label: "概述",
    },
    {
      type: "doc",
      id: "operate/set-up-agent-keys",
      label: "密钥管理",
    },
    {
      type: "category",
      label: "运行验证器",
      link: {
        type: "doc",
        id: "operate/validators/run-validators",
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "operate/validators/validator-signatures-aws",
          label: "AWS 签名存储桶设置",
        },
        {
          type: "doc",
          id: "operate/validators/monitoring-alerting",
          label: "监控与警报",
        },
      ],
    },
    {
      type: "category",
      label: "运行中继器",
      link: {
        type: "doc",
        id: "operate/relayer/run-relayer",
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "operate/relayer/message-filtering",
          label: "消息过滤",
        },
        {
          type: "doc",
          id: "operate/relayer/monitoring-alerting",
          label: "监控与警报",
        },
      ],
    },
    {
      type: "category",
      label: "代理配置",
      link: {
        type: "doc",
        id: "operate/agent-config",
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "operate/config-reference",
          label: "配置参考",
        },
      ],
    },

    {
      type: "category",
      label: "指南",
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: "doc",
          id: "operate/docker-quickstart",
          label: "Docker 快速入门",
        },
        {
          type: "doc",
          id: "operate/deploy-with-terraform",
          label: "使用 Terraform 部署",
        },
        {
          type: "doc",
          id: "guides/avs-operator-guide",
          label: "AVS 操作员指南",
        },
      ],
    },
  ],
};

module.exports = sidebars;
